#!/bin/bash
# sqlline - Script to launch SQL shell on Unix, Linux or Mac OS
echo 'usage : !connect jdbc:ink://localhost:9292 production production'
BINPATH=$(dirname $0)
exec java -Djava.ext.dirs=$BINPATH sqlline.SqlLine "$@"

# End sqlline
