package org.tommy.stationery.ink.enums;

/**
 * Created by kun7788 on 15. 2. 13..
 */
public enum SettingEnum {
    BUCKET_CONNECTION_INITIALPOOLSIZE("BUCKET_CONNECTION_INITIALPOOLSIZE"),
    BUCKET_CONNECTION_MAXPOOLSIZE("BUCKET_CONNECTION_MAXPOOLSIZE"),
    BUCKET_CONNECTION_MINPOOLSIZE("BUCKET_CONNECTION_MINPOOLSIZE"),
    SESSION_TIME_OUT("SESSION_TIME_OUT"),
    TOPOLOGY_RECEIVER_BUFFER_SIZE("TOPOLOGY_RECEIVER_BUFFER_SIZE"),
    TOPOLOGY_TRANSFER_BUFFER_SIZE("TOPOLOGY_TRANSFER_BUFFER_SIZE"),
    TOPOLOGY_EXECUTOR_SEND_BUFFER_SIZE("TOPOLOGY_EXECUTOR_SEND_BUFFER_SIZE"),
    TOPOLOGY_EXECUTOR_RECEIVE_BUFFER_SIZE("TOPOLOGY_EXECUTOR_RECEIVE_BUFFER_SIZE"),
    DUMP_ZOOKEEPER_SERVER("DUMP_ZOOKEEPER_SERVER"),
    DUMP_FLUSH_API_URL("DUMP_FLUSH_API_URL"),
    DUMP_CLEAR_API_URL("DUMP_CLEAR_API_URL"),
    DUMP_API_URL("DUMP_API_URL"),
    REGIST_JOB("REGIST_JOB"),
    STORM_URL("STORM_URL"),
    STORM_HOME("STORM_HOME"),
    STORM_CLIENT_FILEPATH("STORM_CLIENT_FILEPATH"),
    STORM_CLIENT_JAR("STORM_CLIENT_JAR"),
    STORM_CLIENT_MAIN_CLASS("STORM_CLIENT_MAIN_CLASS"),
    STORM_RUN_LOG_FULLPATH("STORM_RUN_LOG_FULLPATH"),
    IS_LOCAL("IS_LOCAL"),
    WORKER_CNT("WORKER_CNT"),
    SPOUT_THREAD_CNT("SPOUT_THREAD_CNT"),
    ESPER_THREAD_CNT("ESPER_THREAD_CNT"),
    LOOKUP_THREAD_CNT("LOOKUP_THREAD_CNT"),
    OUTPUT_THREAD_CNT("OUTPUT_THREAD_CNT"),
    IS_DEBUG("IS_DEBUG"),
    COMMIT_INTERVAL("COMMIT_INTERVAL"),
    STORM_MESSAGE_TIMEOUT_SEC("STORM_MESSAGE_TIMEOUT_SEC"),
    STORM_MAXSPOUTPENDING_NUM("STORM_MAXSPOUTPENDING_NUM"),
    STORM_BATCH_SIZE("STORM_BATCH_SIZE"),
    STORM_CLUSTER_SLAVE_SYSTEM_LOG_PATH("STORM_CLUSTER_SLAVE_SYSTEM_LOG_PATH"),
    STORM_CLUSTER_SLAVE_HOSTS("STORM_CLUSTER_SLAVE_HOSTS"),
    JOB_NAME("JOB_NAME");

    private String name;

    public String getName() {
        return name;
    }

    private SettingEnum(String name) {
        this.name = name;
    }
}
